services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-https://lendapitest.persiansys.ir/api/v1}
        NEXT_PUBLIC_API_REPORT_URL: ${NEXT_PUBLIC_API_REPORT_URL:-https://lendreporttest.persiansys.ir/api/v1}
        NEXT_PUBLIC_AUTH_API_URL: ${NEXT_PUBLIC_AUTH_API_URL:-}
        NEXT_PUBLIC_QUERY_GC_TIME: ${NEXT_PUBLIC_QUERY_GC_TIME:-0}
        NEXT_PUBLIC_QUERY_STALE_TIME: ${NEXT_PUBLIC_QUERY_STALE_TIME:-0}
        NEXT_PUBLIC_QUERY_RETRY: ${NEXT_PUBLIC_QUERY_RETRY:-1}
        NEXT_PUBLIC_SENTRY_DSN: ${NEXT_PUBLIC_SENTRY_DSN:-}
        NEXT_PUBLIC_SENTRY_ENVIRONMENT: ${NEXT_PUBLIC_SENTRY_ENVIRONMENT:-}
    image: lend-site-v2:latest
    ports:
      - "0.0.0.0:${PORT:-3000}:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-https://lendapitest.persiansys.ir/api/v1}
      NEXT_PUBLIC_API_REPORT_URL: ${NEXT_PUBLIC_API_REPORT_URL:-https://lendreporttest.persiansys.ir/api/v1}
      NEXT_PUBLIC_AUTH_API_URL: ${NEXT_PUBLIC_AUTH_API_URL:-}
      TCI_LENDTECH_SECRET: ${TCI_LENDTECH_SECRET:-}
      TCI_LENDTECH_LOGIN_URL: ${TCI_LENDTECH_LOGIN_URL:-}
      NEXT_PUBLIC_QUERY_GC_TIME: ${NEXT_PUBLIC_QUERY_GC_TIME:-0}
      NEXT_PUBLIC_QUERY_STALE_TIME: ${NEXT_PUBLIC_QUERY_STALE_TIME:-0}
      NEXT_PUBLIC_QUERY_RETRY: ${NEXT_PUBLIC_QUERY_RETRY:-1}
      NEXT_PUBLIC_SENTRY_DSN: ${NEXT_PUBLIC_SENTRY_DSN:-}
      NEXT_PUBLIC_SENTRY_ENVIRONMENT: ${NEXT_PUBLIC_SENTRY_ENVIRONMENT:-}
    restart: unless-stopped
