<<<<<<< HEAD
import type { Metadata } from 'next';
=======
import type { Metadata, Viewport } from 'next';
>>>>>>> a47b58a (pwa)
import { Geist, Geist_Mono } from 'next/font/google';

import { NextIntlClientProvider } from 'next-intl';
import { dirFor } from '@/i18n/routing';

import { NuqsProvider } from '@/providers/nuqs';
import { AuthListener } from '@/lib/auth/auth-listener';
import { QueryClientProvider } from '@/lib/query-client/provider';

import '@/lib/env';
import '@/app/globals.css';
import { Toaster } from '@/components/ui/sonner';
<<<<<<< HEAD
=======
import { PwaInstallPrompt } from '@/components/pwa-install-prompt';
>>>>>>> a47b58a (pwa)

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: 'Create Next App',
  description: 'Generated by create next app',
=======
  title: 'Lend Site',
  description: 'Lend financial services platform',
  manifest: '/manifest.json',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'Lend Site',
  },
  formatDetection: {
    telephone: false,
  },
  icons: {
    icon: [
      { url: '/icons/icon-192x192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icons/icon-512x512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: [{ url: '/icons/apple-touch-icon.png', sizes: '180x180', type: 'image/png' }],
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#ffffff' },
    { media: '(prefers-color-scheme: dark)', color: '#000000' },
  ],
  width: 'device-width',
  initialScale: 1,
  minimumScale: 1,
>>>>>>> a47b58a (pwa)
};

export default async function RootLayout({ params, children }: LayoutProps<'/[locale]'>) {
  const { locale } = await params;

  return (
    <html lang={locale} dir={dirFor(locale)}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Toaster toastOptions={{ className: 'IranYekan !important' }} />

        <NextIntlClientProvider>
          <NuqsProvider>
            <AuthListener />
<<<<<<< HEAD
=======
            <PwaInstallPrompt />
>>>>>>> a47b58a (pwa)
            <QueryClientProvider>{children}</QueryClientProvider>
          </NuqsProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
