import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { NextIntlClientProvider } from 'next-intl';
import { dirFor } from '@/i18n/routing';

import { NuqsProvider } from '@/providers/nuqs';
import { AuthListener } from '@/lib/auth/auth-listener';
import { QueryClientProvider } from '@/lib/query-client/provider';

import '@/lib/env';
import '@/app/globals.css';
import { Toaster } from '@/components/ui/sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ params, children }: LayoutProps<'/[locale]'>) {
  const { locale } = await params;

  return (
    <html lang={locale} dir={dirFor(locale)}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Toaster toastOptions={{ className: 'IranYekan !important' }} />

        <NextIntlClientProvider>
          <NuqsProvider>
            <AuthListener />
            <QueryClientProvider>{children}</QueryClientProvider>
          </NuqsProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
